import { Sequelize } from "sequelize";
function valid(Model, payload) {
    return Object.entries(Model.tableAttributes).reduce((valid, [name, field]) => {
        if(valid && !field._autoGenerated && !field.primaryKey && !payload[name]) {
            valid = false;
        }
        return valid;
    }, true)
}

async function checkLogin(Model, request, response){
    try{
        // let sql = `SELECT * FROM accounts WHERE (username = "${request.body.username}" AND password = "${request.body.password}")`;
        // db.all(sql, function(err, rows) {
        //     rows.forEach(function(row){
        //         if(row.username == request.body.username && row.password == request.body.password){
        //             response.status(201).send();
        //         }
        //         else{
        //             response.status(404).send();
        //         }
        //     })
        // })
        console.log(request.query)
        var user = await Model.findOne({where: {email: request.query.email, password: request.query.password}});
        console.log(user);
        if(user === null){
            response.status(404).send({message: "User not found"});
        }
        else{
            response.status(201).send(user);
        }
    }catch(error){
        response.status(500).json(error);
    }
}

async function getRecords(Model, request, response){
    try{
        let records = await Model.findAll();
        if(records.length > 0){
            response.status(200).json(records);
        }
        else{
            response.status(204).send(); //status no content
        }
    }catch(error){
        response.status(500).json(error);
    }
}

async function postRecord(Model, request, response){
    try{
        if(valid(Model, request.body)){
            let record = await Model.create(request.body);
            response.status(201) // status created
            .location(`http://${request.headers.host}${request.baseUrl}${request.url}${request.url.endsWith('/') ? '' : '/'}${record.id}`)
            .send();
        }else{
            response.status(400).send(); //status bad request
        }
    }catch(error){
        response.status(500).json(error);
    }
}

async function deleteRecords(Model, request, response){
    try{
        await Model.truncate();
        response.status(204).send();
    }catch(error){
        response.status(500).json(error);
    }
}

async function getRecord(Model, request, response){
    try{
        let record = await Model.findByPk(request.params.id);
        if(record){
            response.status(200).json(record);
        }else{
            response.status(404).send();
        }
    }catch(error){
        response.status(500).json(error);
    }
}

async function putRecord(Model, request, response){
    try{
        let record = await Model.findByPk(request.params.id);
        if(record){
            if(valid(Model, request.body)){
                await record.update(request.body);
                response.status(204).send();
            }else{
                response.status(400).send();
            }
        }else{
            response.status(404).send();
        }
    }catch(error){
        response.status(500).json(error);
    }
}

async function headRecord(Model, request, response){
    try{
        response.status(await Model.findByPk(request.params.id) ? 204 : 404).send();
    }catch(error){
        response.status(500).json(error);
    }
}

async function patchRecord(Model, request, response){
    try{
        let record = await Model.findByPk(request.params.id);
        if(record){
            Object.entries(request.body).forEach(([name, value]) => record[name] = value);

            await record.save();
            response.status(204).send();
        }else{
            response.status(404).send();
        }
    }catch(error){
        response.status(500).json(error);
    }
}

async function deleteRecord(Model, request, response){
    try{
        let record = await Model.findByPk(request.params.id);
        if(record){
           await record.destroy();
           response.status(204).send();
        }else{
            response.status(404).send();
        }
    }catch(error){
        response.status(500).json(error);
    }
}






export {
    getRecords, postRecord, deleteRecords, getRecord, putRecord, headRecord, patchRecord, deleteRecord, checkLogin
}